name=Opta Linker
version=1.1.1
author=JcDenis <arduino@jcdenis.fr>
maintainer=JcDenis <arduino@jcdenis.fr>
sentence=Findernet Opta toolbox
paragraph=Ready to use library to configure and use Opta board and expansions as Industrial relay.
category=Device Control
url=https://github.com/JcDenis/OptaLinker
architectures=mbed_opta
includes=OptaLinker.h
depends=ArduinoHttpClient (=0.6.1),MQTT (=2.5.3),Arduinojson (=7.4.3),ArduinoRS485 (=1.1.1),ArduinoModbus (=1.0.9),Arduino_Opta_Blueprint (=0.2.9),Arduino_Portenta_OTA (=1.2.1),NTPClient (=3.2.1)
